# The board from an article
# source: https://habrahabr.ru/post/151819/
#
# See the file format in hello.toml


[clues]
columns = """
    8, 14, 17, 20, 23,
    24, 8 12, 5 6, 3 4, 4 1,
    3 7 2, 3 13 1, 3 18 2, 2 10 6 2, 3 7 4 1,
    3 5 5, 3 4 3, 2 4 1, 3 3, 2 3,
    2 2, 3 4, 3 3, 2 2 2, 2 1 2 2,
    1 3 1 1, 1 1 1, 1 2, 1 2 1, 2 7 1,
    1 1 1, 5 1 1, 8 1 1, 3 5 2 2, 9 4 1 2,
    15 3 4, 21 1, 5 11 4, 5 10 3, 3 7 1,
    2 2 1 1 1, 2 2 1 1 1 1 3 1, 1 2 5 1 2 1 1, 1 7 2 9 1 1, 11 5 1 1 1 1,
    8 6 1 1 3 2, 8 2 3 1 2 2 1, 8 2 3 1 1 2 1, 16 2 1 3, 2 6 4 1 2 2,
    3 1 1 2 2 1, 5 1 2 2 3 2, 8 3 3, 11, 2 5,
    1 5, 1 7, 3 6, 5
"""


rows = """
    4
    2 1
    2 1
    1 1 8
    2 1 10 2

    1 1 6 6 1
    1 1 7 4 1
    2 8 3 1
    2 8 6
    2 7 6

    2 7 7
    3 3 11
    2 1 3 6
    2 2 6 1 3
    2 1 2 2 2 1

    3 5 2 1
    3 7 2
    3 5 1
    8 6 4 1
    12 9 1

    7 6 8 2 2
    5 3 2 6 3 3
    4 2 6 2 6 1 3
    4 5 1 2 4 6 1
    4 8 3 3 5 1

    4 9 1 3 5 1
    4 12 3 3 1
    5 5 1 1 1 3 3 2 4
    4 5 1 3 1 5 6 2
    5 5 2 1 1 3 2 2

    5 4 1 1 1 1 5 1
    5 4 2 5 1 1 2
    5 4 2 1 3 1 2 1
    5 3 2 2 4 2 2
    7 3 1 1 1 1 5

    7 2 2 2 8 2
    7 2 4 2 4
    7 2 7
    7 3
    7 2

    8 2
    8 2
    7 2
    7 2
    5 1

    3 2
    3 1
    4 2
    5
    3
"""
