# simplified United Kingdom flag
#
# See the file format in hello.txt

[colors]
defs = [
    'b = (blue) *',
    'r = (red) %',
]

[clues]
columns ="""
    1r 5b 3r 5b 1r
    1r 5b 3r 5b 1r
    2r 4b 3r 4b 2r
    1b 1r 4b 3r 4b 1r 1b
    1b 2r 3b 3r 3b 2r 1b
    2b 1r 3b 3r 3b 1r 2b
    2b 2r 2b 3r 2b 2r 2b
    3b 1r 2b 3r 2b 1r 3b
    3b 2r 1b 3r 1b 2r 3b
    4b 1r 1b 3r 1b 1r 4b
    4b 7r 4b
    5b 5r 5b
    5b 5r 5b
    6b 3r 6b

    15r, 15r, 15r

    6b 3r 6b
    5b 5r 5b
    5b 5r 5b
    4b 7r 4b
    4b 1r 1b 3r 1b 1r 4b
    3b 2r 1b 3r 1b 2r 3b
    3b 1r 2b 3r 2b 1r 3b
    2b 2r 2b 3r 2b 2r 2b
    2b 1r 3b 3r 3b 1r 2b
    1b 2r 3b 3r 3b 2r 1b
    1b 1r 4b 3r 4b 1r 1b
    2r 4b 3r 4b 2r
    1r 5b 3r 5b 1r
    1r 5b 3r 5b 1r
"""

rows ="""
    3r 11b 3r 11b 3r
    2b 3r 9b 3r 9b 3r 2b
    4b 3r 7b 3r 7b 3r 4b
    6b 3r 5b 3r 5b 3r 6b
    8b 3r 3b 3r 3b 3r 8b
    10b 3r 1b 3r 1b 3r 10b

    31r, 31r, 31r

    10b 3r 1b 3r 1b 3r 10b
    8b 3r 3b 3r 3b 3r 8b
    6b 3r 5b 3r 5b 3r 6b
    4b 3r 7b 3r 7b 3r 4b
    2b 3r 9b 3r 9b 3r 2b
    3r 11b 3r 11b 3r
"""

# % % % * * * * * * * * * * * % % % * * * * * * * * * * * % % %
# * * % % % * * * * * * * * * % % % * * * * * * * * * % % % * *
# * * * * % % % * * * * * * * % % % * * * * * * * % % % * * * *
# * * * * * * % % % * * * * * % % % * * * * * % % % * * * * * *
# * * * * * * * * % % % * * * % % % * * * % % % * * * * * * * *
# * * * * * * * * * * % % % * % % % * % % % * * * * * * * * * *
# % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % %
# % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % %
# % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % %
# * * * * * * * * * * % % % * % % % * % % % * * * * * * * * * *
# * * * * * * * * % % % * * * % % % * * * % % % * * * * * * * *
# * * * * * * % % % * * * * * % % % * * * * * % % % * * * * * *
# * * * * % % % * * * * * * * % % % * * * * * * * % % % * * * *
# * * % % % * * * * * * * * * % % % * * * * * * * * * % % % * *
# % % % * * * * * * * * * * * % % % * * * * * * * * * * * % % %
